export const Permissions = {
  CAMERA_ACCESS: 'CAMERA_ACCESS',
  STORAGE_WRITE: 'STORAGE_WRITE',
  STORAGE_READ: 'STORAGE_READ',
  NETWORK_ACCESS: 'NETWORK_ACCESS',
  NOTIFICATIONS: 'NOTIFICATIONS',
  BACKGROUND_PROCESS: 'BACKGROUND_PROCESS'
};

export default Permissions;
